services:
    dev:
        build: .
        image: mimo_dev_img
        container_name: mimo_dev
        #        ports:
        #    - "${DEV_API_PORT}:8080"
        #    - "${DEV_SOCKET_PORT}:65432"
        networks:
            - mimo
        environment:
            - "MYSQL_URL=${DEV_MYSQL_URL}"
            - "MYSQL_USERNAME=${DEV_MYSQL_USERNAME}"
            - "MYSQL_PASSWORD=${DEV_MYSQL_PASSWORD}"
            - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
    green:
        build: .
        image: mimo_green_img
        container_name: mimo_green
        # ports:
        #    - "${GREEN_API_PORT}:8080"
        #    - "${GREEN_SOCKET_PORT}:65432"
        networks:
            - mimo
        environment:
            - "MYSQL_URL=${OPS_MYSQL_URL}"
            - "MYSQL_USERNAME=${OPS_MYSQL_USERNAME}"
            - "MYSQL_PASSWORD=${OPS_MYSQL_PASSWORD}"
            - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
    blue:
        build: .
        image: mimo_blue_img
        container_name: mimo_blue
        #ports:
        #    - "${BLUE_API_PORT}:8080"
        #    - "${BLUE_SOCKET_PORT}:65432"
        networks:
            - mimo
        environment:
            - "MYSQL_URL=${OPS_MYSQL_URL}"
            - "MYSQL_USERNAME=${OPS_MYSQL_USERNAME}"
            - "MYSQL_PASSWORD=${OPS_MYSQL_PASSWORD}"
            - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"

networks:
    mimo:
        name: mimo-network
        external: true
