services:
    master:
        build:
            context: .
            dockerfile: Dockerfile.master
        image: jenkins_master
        container_name: jenkins_master
        env_file:
            - .env
        ports:
            - "${JENKINS_MASTER_PORT_0}:8080"
            - "${JENKINS_MASTER_PORT_1}:50000"
        volumes:
            - master:/var/jenkins_home
        networks:
            - mimo
        environment:
            - JENKINS_OPTS="--prefix=/jenkins"

    agent:
        build:
            context: .
            dockerfile: Dockerfile.agent
        image: jenkins_agent
        container_name: jenkins_agent
        env_file:
            - .env
        ports:
            - "${JENKINS_AGENT_PORT_0}:8080"
            - "${JENKINS_AGENT_PORT_1}:50000"
        volumes:
            - agent:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - mimo_agent

networks:
    mimo:
        name: jenkins-network
        external: true

volumes:
    master:
        name: jenkins-volume
        external: true

    agent:
        name: jenkins_agent-volume
        external: true

