services:
    jenkins:
        build: .
        image: jenkins
        container_name: jenkins
        env_file:
            - .env
        ports:
            - "${JENKINS_PORT}:8080"
            - "${JENKINS_PORT_2}:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - mimo_dev
            - mimo_ops
        environment:
            - JENKINS_OPTS="--prefix=/jenkins"

networks:
    mimo_dev:
        name: mimo_dev-network
        external: true
    mimo_ops:
        name: mimo_ops-network
        external: true

volumes:
    jenkins:
        name: jenkins-volume
        external: true

