services:
    master:
        build: Dockerfile.master
        image: jenkins_master
        container_name: jenkins_master
        env_file:
            - .env
        ports:
            - "${JENKINS_MASTER_PORT_0}:8080"
            - "${JENKINS_MASTER_PORT_1}:50000"
        volumes:
            - master:/var/jenkins_home
        networks:
            - mimo_dev
            - mimo_ops
        environment:
            - JENKINS_OPTS="--prefix=/jenkins"

    dev:
        build: Dockerfile.dev
        image: jenkins_dev
        container_name: jenkins_dev
        env_file:
            - .env
        ports:
            - "${JENKINS_DEV_PORT_0}:8080"
            - "${JENKINS_DEV_PORT_1}:50000"
        volumes:
            - dev:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - mimo_dev


    ops:
        build: Dockerfile.ops
        image: jenkins_ops
        container_name: jenkins_ops
        env_file:
            - .env
        ports:
            - "${JENKINS_OPS_PORT_0}:8080"
            - "${JENKINS_OPS_PORT_1}:50000"
        volumes:
            - ops:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - mimo_ops


networks:
    mimo_dev:
        name: mimo_dev-network
        external: true
    mimo_ops:
        name: mimo_ops-network
        external: true

volumes:
    master:
        name: jenkins-volume
        external: true

    dev:
        name: jenkins_dev-volume
        external: true

    ops:
        name: jenkins_ops-volume
        external: true

