services:
    master:
        build:
            context: .
            dockerfile: Dockerfile.master
        image: jenkins_master
        container_name: jenkins_master
        env_file:
            - .env
        ports:
            - "${JENKINS_MASTER_PORT_0}:8080"
            - "${JENKINS_MASTER_PORT_1}:50000"
        volumes:
            - master-vol:/var/jenkins_home
        networks:
            - jenkins-net
        environment:
            - JENKINS_OPTS="--prefix=/jenkins"

    agent:
        build:
            context: .
            dockerfile: Dockerfile.agent
        image: jenkins_agent
        container_name: jenkins_agent
        env_file:
            - .env
        ports:
            - "${JENKINS_AGENT_PORT_0}:8080"
            - "${JENKINS_AGENT_PORT_1}:50000"
        volumes:
            - agent-vol:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - jenkins-net

networks:
    jenkins-net:
        name: jenkins-network
        external: true

volumes:
    master-vol:
        name: jenkins_master-volume
        external: true

    agent-vol:
        name: jenkins_agent-volume
        external: true

