services:
  nginx:
    build: .
    image: nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - "${SSL_CERT_PATH}:/etc/nginx/ssl/fullchain.pem"
      - "${SSL_KEY_PATH}:/etc/nginx/ssl/privkey.pem"
      - "./http.conf:/etc/nginx/conf.d/http.conf"
      - "./stream.conf:/etc/nginx/conf.d/stream.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mimo

networks:
  mimo:
    name: mimo-network
    external: true
