services:
    db_ops:
        build: .
        image: db_ops
        container_name: db_ops
        env_file:
            - .env
        ports:
            - "${DATABASE_PORT_0}:3306"
            - "${DATABASE_PORT_1}:33060"
        volumes:
            - volume:/var/lib/mysql
        networks:
            - network

volumes:
    volume:
        name: db_ops-volume
        external: true

networks:
    network:
        name: mimo_ops-network
        external: true

